project:
  type: website
  output-dir: docs

website:
  title: "LLM Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: vignettes/telemetry.qmd
        text: Telemetry

format:
  html:
    theme: cosmo
    toc: true
